version: '3'
services:
  mongosync:
    container_name: mongosync
    build: .
    image: mongosync
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
  environment:
    # CHUNK_CONFS:
#      SOURCE:
#      TARGET:
#      DB_MAP:
#      TS_FILE:
#      AWAIT: